### ISSUE TITLE
tinfoil.io down / not related to titledb

### ISSUE THREAD

**Issue by Ghost0159** [blawar/titledb_04082025#1]
Hey, I didn’t know where to talk about this, and I’m sorry if this isn’t the right place.

tinfoil.io has been down for over a week, and tinfoil.media isn’t up to date.

Thanks in advance, and sorry for the inconvenience.

PS: Merry xmas to you, Blawar!

**Comment by blawar** [comment]
I got it back up. Please open up an issue if it hasn't updated in 1 business day.

**Comment by Ghost0159** [comment]
Ok great thanks
